In [1]:
import pandas as pd
import numpy as np


In [2]:
car = pd.read_csv('cardekho_dataset.csv')

In [8]:
car.head()

Unnamed: 0       car_name    brand     model  vehicle_age  km_driven  \
0           0    Maruti Alto   Maruti      Alto            9     120000   
1           1  Hyundai Grand  Hyundai     Grand            5      20000   
2           2    Hyundai i20  Hyundai       i20           11      60000   
3           3    Maruti Alto   Maruti      Alto            9      37000   
4           4  Ford Ecosport     Ford  Ecosport            6      30000   

  fuel_type transmission_type  mileage  selling_price  
0    Petrol            Manual    19.70         120000  
1    Petrol            Manual    18.90         550000  
2    Petrol            Manual    17.00         215000  
3    Petrol            Manual    20.92         226000  
4    Diesel            Manual    22.77         570000

In [4]:
car.shape()

TypeError: 'tuple' object is not callable

In [5]:
car.shape

(15411, 9)

In [6]:
car.info

<bound method DataFrame.info of        sr. no     brand     model  vehicle_age  km_driven fuel_type  \
0           0    Maruti      Alto            9     120000    Petrol   
1           1   Hyundai     Grand            5      20000    Petrol   
2           2   Hyundai       i20           11      60000    Petrol   
3           3    Maruti      Alto            9      37000    Petrol   
4           4      Ford  Ecosport            6      30000    Diesel   
...       ...       ...       ...          ...        ...       ...   
15406   19537   Hyundai       i10            9      10723    Petrol   
15407   19540    Maruti    Ertiga            2      18000    Petrol   
15408   19541     Skoda     Rapid            6      67000    Diesel   
15409   19542  Mahindra    XUV500            5    3800000    Diesel   
15410   19543     Honda      City            2      13000    Petrol   

      transmission_type  mileage  selling_price  
0                Manual    19.70         120000  
1              

In [7]:
    car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sr. no             15411 non-null  int64  
 1   brand              15411 non-null  object 
 2   model              15411 non-null  object 
 3   vehicle_age        15411 non-null  int64  
 4   km_driven          15411 non-null  int64  
 5   fuel_type          15411 non-null  object 
 6   transmission_type  15411 non-null  object 
 7   mileage            15411 non-null  float64
 8   selling_price      15411 non-null  int64  
dtypes: float64(1), int64(4), object(4)
memory usage: 1.1+ MB


In [8]:
car['year'] = unique

NameError: name 'unique' is not defined

In [3]:
car['fuel_type'].unique()

array(['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric'], dtype=object)

In [11]:
car['vehicle_age'].unique()

array([ 9,  5, 11,  6,  8,  3,  2,  4,  7, 10, 14, 12,  1, 15, 13, 16, 17,
       18, 29, 19,  0, 21, 22, 25], dtype=int64)

In [12]:
backup = car.copy()

In [3]:
car['vehicle_age'] = 2023-car['vehicle_age']

In [4]:
car['vehicle_age'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 15411 entries, 0 to 15410
Series name: vehicle_age
Non-Null Count  Dtype
--------------  -----
15411 non-null  int64
dtypes: int64(1)
memory usage: 120.5 KB


In [5]:
car['vehicle_age'].unique()

array([2014, 2018, 2012, 2017, 2015, 2020, 2021, 2019, 2016, 2013, 2009,
       2011, 2022, 2008, 2010, 2007, 2006, 2005, 1994, 2004, 2023, 2002,
       2001, 1998], dtype=int64)

In [11]:
car.describe()

Unnamed: 0   vehicle_age     km_driven       mileage  selling_price
count  15411.000000  15411.000000  1.541100e+04  15411.000000   1.541100e+04
mean    9811.857699   2016.963662  5.561648e+04     19.701151   7.749711e+05
std     5643.418542      3.013291  5.161855e+04      4.171265   8.941284e+05
min        0.000000   1994.000000  1.000000e+02      4.000000   4.000000e+04
25%     4906.500000   2015.000000  3.000000e+04     17.000000   3.850000e+05
50%     9872.000000   2017.000000  5.000000e+04     19.670000   5.560000e+05
75%    14668.500000   2019.000000  7.000000e+04     22.700000   8.250000e+05
max    19543.000000   2023.000000  3.800000e+06     33.540000   3.950000e+07

In [6]:
car.drop(columns=['Unnamed: 0'], inplace=True)

In [13]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   car_name           15411 non-null  object 
 1   brand              15411 non-null  object 
 2   model              15411 non-null  object 
 3   vehicle_age        15411 non-null  int64  
 4   km_driven          15411 non-null  int64  
 5   fuel_type          15411 non-null  object 
 6   transmission_type  15411 non-null  object 
 7   mileage            15411 non-null  float64
 8   selling_price      15411 non-null  int64  
dtypes: float64(1), int64(3), object(5)
memory usage: 1.1+ MB


In [7]:
car.drop(car[car['selling_price'] > 6000000].index, inplace=True)


In [8]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15346 entries, 0 to 15410
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   car_name           15346 non-null  object 
 1   brand              15346 non-null  object 
 2   model              15346 non-null  object 
 3   vehicle_age        15346 non-null  int64  
 4   km_driven          15346 non-null  int64  
 5   fuel_type          15346 non-null  object 
 6   transmission_type  15346 non-null  object 
 7   mileage            15346 non-null  float64
 8   selling_price      15346 non-null  int64  
dtypes: float64(1), int64(3), object(5)
memory usage: 1.2+ MB


In [9]:
car.to_csv('cleaned_car.csv')

In [10]:
cols_drop = ['selling_price','fuel_type']
x=car.drop(columns=cols_drop)
y=car['selling_price']


In [85]:
x

car_name     brand     model  vehicle_age  km_driven  \
0          Maruti Alto    Maruti      Alto         2014     120000   
1        Hyundai Grand   Hyundai     Grand         2018      20000   
2          Hyundai i20   Hyundai       i20         2012      60000   
3          Maruti Alto    Maruti      Alto         2014      37000   
4        Ford Ecosport      Ford  Ecosport         2017      30000   
...                ...       ...       ...          ...        ...   
15406      Hyundai i10   Hyundai       i10         2014      10723   
15407    Maruti Ertiga    Maruti    Ertiga         2021      18000   
15408      Skoda Rapid     Skoda     Rapid         2017      67000   
15409  Mahindra XUV500  Mahindra    XUV500         2018    3800000   
15410       Honda City     Honda      City         2021      13000   

      transmission_type  mileage  
0                Manual    19.70  
1                Manual    18.90  
2                Manual    17.00  
3                Manual    20.92  
4                Manual    22.77  
...                 ...      ...  
15406            Manual    19.81  
15407            Manual    17.50  
15408            Manual    21.14  
15409            Manual    16.00  
15410         Automatic    18.00  

[15346 rows x 7 columns]

In [87]:
y

0         120000
1         550000
2         215000
3         226000
4         570000
          ...   
15406     250000
15407     925000
15408     425000
15409    1225000
15410    1200000
Name: selling_price, Length: 15346, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [12]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder

In [19]:
ohe = OneHotEncoder()

In [20]:
ohe.fit(x[['brand','model']])

OneHotEncoder()

In [21]:
ohe = OneHotEncoder()
ohe.fit(x[['brand','model']])

OneHotEncoder()

In [22]:
ohe.fit(x)

OneHotEncoder()

In [23]:
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [28]:
categorical_columns = ['car_name','brand', 'model', 'transmission_type']  # Adjust column names as per your data

column_trans = make_column_transformer(
    (OneHotEncoder(handle_unknown='ignore'), categorical_columns),  # One-hot encode categorical columns
    remainder='passthrough'
)

In [29]:
lr = LinearRegression()

In [30]:
pipe = make_pipeline(column_trans,lr)

In [31]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['car_name', 'brand', 'model',
                                                   'transmission_type'])])),
                ('linearregression', LinearRegression())])

In [32]:
y_pred = pipe.predict(x_test)

In [33]:
scores=[]
for i in range(1000):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(x_train,y_train)
    y_pred=pipe.predict(x_test)
    scores.append(r2_score(y_test,y_pred))

In [34]:
np.argmax(scores)

322

In [35]:
scores[np.argmax(scores)]


0.6820746502731392

In [55]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   car_name           15411 non-null  object 
 1   brand              15411 non-null  object 
 2   model              15411 non-null  object 
 3   vehicle_age        15411 non-null  int64  
 4   km_driven          15411 non-null  int64  
 5   fuel_type          15411 non-null  object 
 6   transmission_type  15411 non-null  object 
 7   mileage            15411 non-null  float64
 8   selling_price      15411 non-null  int64  
dtypes: float64(1), int64(3), object(5)
memory usage: 1.1+ MB


In [69]:
import pickle

In [57]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [58]:
pipe.predict(pd.DataFrame([['maruti','alto','2014','12000','petrol','manual','19.70']], columns =['brand','model','vehicle_age','km_driven','fuel_type','transmission_type','mileage']))

array([834914.09499148])

In [90]:
from sklearn.ensemble import RandomForestRegressor

In [91]:
x_encoded = pd.get_dummies(x, columns=['car_name','brand', 'model', 'transmission_type'], drop_first=True)


In [92]:
x_train, x_test, y_train, y_test = train_test_split(x_encoded, y, test_size=0.2, random_state=42)

In [93]:
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)  # Example hyperparameters


In [94]:
rf_model.fit(x_train, y_train)


RandomForestRegressor(random_state=42)

In [95]:
y_pred = rf_model.predict(x_test)

In [96]:
r2 = r2_score(y_test, y_pred)
r2

0.934851940141106

In [97]:
pickle.dump(pipe,open('RandomForestRegression.pkl','wb'))

In [99]:
pipe.predict(pd.DataFrame([['Maruti Alto','maruti','alto','2014','12000','petrol','manual','19.70']], columns =['car_name','brand','model','vehicle_age','km_driven','fuel_type','transmission_type','mileage']))

array([821353.61525282])

In [14]:
import sklearn


from sklearn.metrics import classification_report

from sklearn.datasets import load_breast_cancer

from sklearn.ensemble import GradientBoostingClassifier

In [15]:
x,y = car.drop('y',axis=1),car.y

test_size = 0.30 # taking 70:30 training and test set

seed = 7 # Random number seeding for repeatability of the code

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=test_size, random_state=seed)

KeyError: "['y'] not found in axis"